on:
  issues:
    types: [opened]

concurrency: 
  group: issue

permissions:
  issues: write
  contents: write

jobs:
  issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run:  python3 main.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          XAI_TOKEN: ${{ secrets.XAI_TOKEN }}
          REPO: ${{ github.repository }}
          ISSUE: ${{ github.event.issue.number }}
      - run: |
          git add source/_posts
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "new post: issue #${{ github.event.issue.number }}"
          git push origin main -f
